name: notetakingapp
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.1


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_sign_in: ^7.1.1
  firebase_auth: ^6.0.2
  firebase_core: ^4.1.0
  cloud_firestore: ^6.0.1
  flutter_screenutil: ^5.9.3
  dio: ^5.9.0
  very_good_analysis: ^9.0.0
  internet_connection_checker_plus: ^2.7.2
  fpdart: ^1.1.1
  image_picker: ^1.2.0
  flutter_native_splash: ^2.4.6
  flutter_bloc: ^9.1.1
  freezed: ^3.2.0
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  get_it: ^8.2.0
  shared_preferences: ^2.5.3
  auto_route: ^10.1.2
  top_snackbar_flutter: ^3.3.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  uuid: ^4.5.1
  drift: ^2.28.1
  sqlite3_flutter_libs: ^0.5.39
  path_provider: ^2.1.5
  path: ^1.9.1
  flutter_gemini: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^6.0.0
  build_runner: ^2.7.1
  json_serializable: ^6.11.0
  auto_route_generator: ^10.1.0
  drift_dev: ^2.28.2


flutter:

  uses-material-design: true
  
  assets:
    - assets/localization/
    - assets/icons/